name: Docker Image CI

on:
  push:
    branches: [ "master", "docker-test" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the server Docker image
      run: docker build server/ --file server/Dockerfile --tag todolist-server:$(date +%s)
    - name: Build the client Docker image
      run: docker build client/ --file client/Dockerfile --tag todolist-client:$(date +%s)
